### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by nickdotzip** [spinfish/amethyst#1]
![image](https://user-images.githubusercontent.com/42217808/132805866-3eeba044-78a6-4be2-a436-314c70585509.png)
this is the only issue
fix pls <3

**Comment by spinfish** [comment]
Hi, apologies for the very late response. What plugin are you using for this?

**Comment by nickdotzip** [comment]
No worries, I am not entirely sure what you mean by plugin, but this is on BetterDiscord and I got it from Theme Repo. If I'm misunderstanding, please explain :)

**Comment by nickdotzip** [comment]
Ohh! I get what you are saying, this is SpotifyControls by DevilBro https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls/

**Comment by spinfish** [comment]
Hello, am really sorry about the very late response, I'll take a look at this plugin tomorrow and see what I can do!! I actually uninstalled BetterDiscord so I'll also need to reinstall that. Again I'm very sorry for the delay D:

**Comment by spinfish** [comment]
Fixed in 0c875a1b1483c4e62b92674424ad056145327ba8 :)
